website: Fix build when public dir is already populated
All CGI scripts are set with 555 permission mode in the post-build
target, and this makes the following builds hang if not cleaned the
public (temp) directory before or changed CGI permissions to 755.

Error: Error building site: process: readAndProcessContent: open
/doc/website/public/cgi/mailindex.cgi: permission denied

PR:		256352
Reviewed by:	lwhsu wosch
Differential Revision: https://reviews.freebsd.org/D34641